"""
全局配置参数模块
这个文件包含所有NANDHardwareSimulator和GPT-2硬件加速的配置参数
"""

# 基础硬件参数
QUANTIZATION_BITS = 8
MEAN = 1.0
SCALE = 0.001
CURRENT_VARIATION_MODE = False
MAX_CURRENT_SUM = 128
BLOCKS_PER_OPERATION = 32
MAX_CURRENT = 160
SYMMETRIC = False
# 硬件架构参数
NUM_TIA_TIMES_ADC = 125
PLANES_PER_DIE = 4
LAYER_PER_DIE = 32
BLOCKS_PER_PLANE = 216
TSG_PER_BLOCK = 10
BITLINES_PER_PLANE = 131072
Y_LOST = 0
TIA_NUM_BASE = 36000
# 硬件时序参数（us）
WL_SETUP_TIME_BASE = 7.0
WL_SWITCH_TIME = 2.0
TSG_SWITCH_TIME = 0.8
BL_SWITCH_TIME = 13.0
TIA_CONVERSION_TIME = 0.25
ADC_CONVERSION_TIME_BASE = 0.002
WRITE_TIME = 100.0
# 电学参数 (A)
TSG_WL_CURRENT = 0.06741
BL_CURRENT = 1.5e-07
VCC = 2.5
TIA_ADC_POWER_BASE = 0.0005
BG_CURRENT=96.732e-3          # 背景电流/block
# 模型与日志参数
ENABLE_MONITORING = True
VISUALIZE = False
# 生成参数
DEFAULT_MAX_LENGTH = 4
DEFAULT_TEMPERATURE = 1.0
DEFAULT_TOP_K = 50
CONFIG_PATH = "E:/coda/GPT2-Hardware/Output"

PROMPT = "How is the weather today?"
